on: 
  push: 
    branches: [ CD ] 
  pull_request: 
    branches: [ CD ] 

jobs: 
  deploy: 
    
    
    runs-on: ubuntu-latest 
    steps: 
    - name: Prepare key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bastion-key.pem && chmod 777 ~/.ssh/bastion-key.pem
    - name: Use agent
      run: | 
        mkdir ~/.ssh && chmod 777 ~/.ssh && touch ~/.ssh/bastion-key.pem
        sudo apt-get update -y 
        sudo apt-get install -y expect
        eval `ssh-agent -s`
        echo $'#!/usr/bin/expect -f \n spawn ssh-add ~/.ssh/bastion-key.pem \n expect "Enter passphrase for /home/runner/.ssh/bastion-key.pem:" \n send "${{ secrets.SSH_PASSPHRASE }}" \n interact' > ./prep.sh
        chmod +x ./prep.sh 
        ./prep.sh
     
      shell: bash
    - run: ${{ secrets.SSH_PASSPHRASE }}
    - name: Bastion AuthN
      run: ssh -tt -i ~/.ssh/bastion-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_IP }}
    - name: Bastion connection agreement
      run : ${{ secrets.SSH_PASSPHRASE }}
    - name: App AuthN
      run: ssh ubuntu@${{ secrets.APP_IP }}
    - name: App connection agreement
      run: yes  
    - run : ${{ secrets.SSH_PASSPHRASE }}
    - run:  ^C
    
    - name: AuthN to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_ID }}
        aws-secret-access-key: ${{ secrets.ECR_SECRET }}
        aws-region: ${{ secrets.ECR_REGION }}
    - uses: aws-actions/amazon-ecr-login@v1
      
    - name: Docker pull
      run: docker pull 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr
    - name: Docker deploy
      run: docker start 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr
      
    - name: Logout
      run:  docker logout
    - name: Kill agent
      run: kill $SSH_AGENT_PID
