on: 
  push: 
    branches: [ CD ] 
  pull_request: 
    branches: [ CD ] 

jobs: 
  deploy: 
  
    
    runs-on: ubuntu-latest 
    env: 
      BASTION: ssh -tt -i bastion-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_IP }}
    steps: 
    - uses: actions/checkout@v2
    - name: Prep 
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > bastion-key.pem 
        chmod 400 bastion-key.pem 
    - name: Put to Bastion
      run: |
        $BASTION $'echo "${{ secrets.SSH_PRIVATE_KEY }}" > bastion-key.pem &&
        chmod 400 bastion-key.pem &&
        APP="ssh -tt -i bastion-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.APP_IP }}" &&
        $APP \'
        docker rm -f $(docker stop petclinic) &&
        docker rmi -f $(docker images 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr:latest -q) &&
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 176361202031.dkr.ecr.us-east-1.amazonaws.com &&
        docker pull 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr:latest &&
        docker run -d -p 8080:8080 --name petclinic 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr:latest &&
        docker logout
        \'
        '
    - name: Kill agent
      run: kill $SSH_AGENT_PID
