on: 
  push: 
    branches: [ CD ] 
  pull_request: 
    branches: [ CD ] 

jobs: 
  deploy: 
    
    
    runs-on: ubuntu-latest 
    steps: 
#    - run: mkdir ~/.ssh && touch ~/.ssh/bastion-key.pem
 #   - name: Prepare key
 #     run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bastion-key.pem && chmod 400 ~/.ssh/bastion-key.pem
    - name: Use agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#      run: eval "$(ssh-agent -c)"
#    - run: ssh-add ~/.ssh/bastion-key.pem
#    - run: ${{ secrets.SSH_PASSPHRASE }}
    - name: Bastion AuthN
      run: ssh -A ec2-user@${{ secrets.BASTION_IP }}
    - name: Bastion connection agreement
      run: yes
    - run : ${{ secrets.SSH_PASSPHRASE }}
    - run:  ^C
    - name: App AuthN
      run: ssh ubuntu@${{ secrets.APP_IP }}
    - name: App connection agreement
      run: yes  
    - run : ${{ secrets.SSH_PASSPHRASE }}
    - run:  ^C
    
    - name: AuthN to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ECR_ID }}
        aws-secret-access-key: ${{ secrets.ECR_SECRET }}
        aws-region: ${{ secrets.ECR_REGION }}
    - uses: aws-actions/amazon-ecr-login@v1
      
    - name: Docker pull
      run: docker pull 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr
    - name: Docker deploy
      run: docker start 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr
      
    - name: Logout
      run:  docker logout
    - name: Kill agent
      run: kill $SSH_AGENT_PID
