on: 
  push: 
    branches: [ CD ] 
  pull_request: 
    branches: [ CD ] 

jobs: 
  deploy: 
    
    
    runs-on: ubuntu-latest 
    steps: 

    - name: AuthN
      run: | 
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > bastion-key.pem 
        chmod 400 bastion-key.pem
        ssh -tt -A -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_IP }}
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > bastion-key.pem 
        chmod 400 bastion-key.pem
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.APP_IP }}
    
    - name: AuthN to AWS
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 176361202031.dkr.ecr.us-east-1.amazonaws.com
      
    - name: Docker pull
      run: docker pull 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr
    - name: Docker deploy
      run: docker stop $CONTAINER && CONTAINER=$(docker run -p 8080:8080 -d 176361202031.dkr.ecr.us-east-1.amazonaws.com/ecr:latest)
      
    - name: Logout
      run:  docker logout
    - name: Kill agent
      run: kill $SSH_AGENT_PID
